# SPDX-FileCopyrightText: Copyright (c) 2023-2026 Yegor Bugayenko
# SPDX-License-Identifier: MIT

# Ticks accumulated after the evaluation of a DFG.
# Author:: Yegor Bugayenko (yegor256@gmail.com)
# Copyright:: Copyright (c) 2023-2026 Yegor Bugayenko
# License:: MIT
class Damsi::Ticks
  def initialize
    @ticks = {}
  end

  # Add a message in properly formatted LaTeX. If the TeX syntax
  # is broken, there will be a runtime problem later.
  def push(tick, tex)
    @ticks[tick] = [] if @ticks[tick].nil?
    @ticks[tick].push(tex)
  end

  def to_latex(log)
    total = @ticks.count
    if total.zero?
      log.info('no ticks')
      return
    end
    log.debug("This tabular is auto-generated by damsi, at #{Time.now}")
    log.info("\\begin{tabular}{#{'l' * total}}")
    pos = 0
    @ticks.each_value do |t|
      log.info("  #{'\\hspace*{1em} & ' * pos} \\multicolumn{#{total - pos}}{l}{\\begin{tabular}{|l}")
      t.each do |e|
        log.info("    #{e} \\\\")
      end
      log.info('  \\end{tabular}} \\\\')
      pos += 1
    end
    log.info('\\end{tabular}')
  end
end
